name: Deploy Frontend to Github Pages

on:
  push:
    branches:
      - master
    paths:
      - 'advanced/**'

jobs:
  deploy:
    name: CD Pipeline
    runs-on: ubuntu-20.04
    env:
      working-directory: './advanced'
    strategy:
      matrix:
        node-version: ['16.x']
    steps:
      # Checkout
      - uses: actions/checkout@v3

      # Install Node.js
      - name: Install Node.js ${{ matrix.node-version }}
        working-directory: ${{ env.working-directory }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install Node.js dependencies
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install

      # Create ./static/links.js File
      - name: Create ./static/links.js File
        working-directory: ${{ env.working-directory }}
        run: npm run build

      # Deploy with Github Pages
      - name: Deploy
        working-directory: ${{ env.working-directory }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./advanced
